# -*- coding: utf-8 -*-
"""附件规则范围配置。

将附件规则范围独立到此文件，便于用户直接调整数值区间。
"""

# 附件规则范围（来自“附件属性规则指南”，仅在字段存在时夹紧）
MOD_PROFILE_RANGES = {
    "muzzle_suppressor": {
        "Ergonomics": (-15, -8),
        "CameraRecoil": (-8, -3),
        "VerticalRecoil": (-18, -10),
        "HorizontalRecoil": (-12, -6),
        "Dispersion": (-5, -1),
        "Accuracy": (-5, 5),
        "Velocity": (0, 3),
        "Loudness": (-40, -20),
        "Flash": (-80, -30),
        "ModMalfunctionChance": (10, 25),
        "DurabilityBurnModificator": (1.2, 1.5),
        "AimSpeed": (-20, -8),
    },
    "muzzle_flashhider": {
        "Ergonomics": (-5, -2),
        "CameraRecoil": (-2, -1),
        "VerticalRecoil": (-5, -2),
        "HorizontalRecoil": (-3, -1),
        "Dispersion": (-2, 2),
        "Loudness": (0, 10),
        "Flash": (-70, -40),
        "AimSpeed": (0, 0),
    },
    "muzzle_brake": {
        "Ergonomics": (-6, -3),
        "CameraRecoil": (-10, -3),
        "VerticalRecoil": (-24, -14),
        "HorizontalRecoil": (-18, -10),
        "Dispersion": (-5, -2),
        "Accuracy": (-2, -1),
        "Velocity": (0, 0),
        "Loudness": (10, 20),
        "Flash": (3, 15),
        "AimSpeed": (-2, 3),
    },
    "muzzle_thread": {
        "Ergonomics": (0, 1),
        "CameraRecoil": (0, 0),
        "VerticalRecoil": (0, 0),
        "HorizontalRecoil": (0, 0),
        "Dispersion": (0, 0),
        "Accuracy": (0, 0),
        "Velocity": (0, 0),
        "Loudness": (0, 0),
        "Flash": (0, 0),
        "ModMalfunctionChance": (0, 0),
        "DurabilityBurnModificator": (1.0, 1.05),
        "AimSpeed": (0, 0),
    },
    # 枪口转接口（muzzle_*_adapter）
    "muzzle_adapter": {
        "Ergonomics": (-2, 0),
        "Flash": (-5, 5),
        "DurabilityBurnModificator": (1.0, 1.1),
    },
    # 弹匣容量分档建议：
    # magazine_compact  <= 20 发
    # magazine_standard 21-40 发
    # magazine_extended 41-60 发
    # magazine_drum     >= 61 发
    "magazine_compact": {
        "Ergonomics": (0, 6),
        "ReloadSpeed": (0, 8),
        "LoadUnloadModifier": (5, 15),
        "CheckTimeModifier": (-3, 1),
        "ModMalfunctionChance": (-3, 1),
        "AimSpeed": (0, 4),
        "Handling": (0, 5),
    },
    "magazine_standard": {
        "Ergonomics": (-3, 1),
        "ReloadSpeed": (-4, 3),
        "LoadUnloadModifier": (3, 10),
        "CheckTimeModifier": (0, 4),
        "ModMalfunctionChance": (-1.5, 1.5),
        "AimSpeed": (-3, 1),
        "Handling": (-3, 1),
    },
    "magazine_extended": {
        "Ergonomics": (-8, -3),
        "ReloadSpeed": (-10, -1),
        "LoadUnloadModifier": (6, 15),
        "CheckTimeModifier": (2, 8),
        "ModMalfunctionChance": (1, 2),
        "AimSpeed": (-6, -1),
        "Handling": (-6, -2),
    },
    "magazine_drum": {
        "Ergonomics": (-15, -8),
        "ReloadSpeed": (-20, -5),
        "LoadUnloadModifier": (12, 25),
        "CheckTimeModifier": (6, 14),
        "ModMalfunctionChance": (3, 5),
        "AimSpeed": (-10, -3),
        "Handling": (-12, -4),
    },
    # 兼容旧逻辑：在未启用容量分档识别前，magazine 先对齐 standard。
    "magazine": {
        "Ergonomics": (-3, 1),
        "ReloadSpeed": (-4, 3),
        "LoadUnloadModifier": (3, 10),
        "CheckTimeModifier": (0, 4),
        "ModMalfunctionChance": (-1.2, 1.2),
        "AimSpeed": (-3, 1),
        "Handling": (-3, 1),
    },
    "gasblock": {
        "Ergonomics": (0, 2),
        "VerticalRecoil": (-2, 0),
        "HorizontalRecoil": (-1, 0),
        "ModMalfunctionChance": (-2, 5),
        "DurabilityBurnModificator": (0.95, 1.05),
        "HeatFactor": (0.98, 1.03),
        "CoolFactor": (0.98, 1.02),
        "Flash": (-3, 3),
    },
    "scope_magnified": {
        "AimSpeed": (-10, -5),
        "Accuracy": (3, 8),
        "AimStability": (5, 10),
        "Ergonomics": (-10, -5),
        "Handling": (-10, -5),
    },
    "scope_red_dot": {
        "AimSpeed": (2, 5),
        "AimStability": (0, 5),
        "Ergonomics": (-1, 3),
    },
    "iron_sight": {
        "AimSpeed": (0, 3),
        "Ergonomics": (0, 2),
    },
    # 枪托细分：
    # stock_fixed       固定枪托/全尺寸枪托
    # stock_folding     折叠/伸缩/紧凑枪托
    # stock_ads_support 高基座或特殊设计（允许开镜）
    "stock_fixed": {
        "VerticalRecoil": (-15, -10),
        "HorizontalRecoil": (-10, -6),
        "CameraRecoil": (-20, -12),
        "Convergence": (12, 20),
        "AimSpeed": (-10, -3),
        "AimStability": (10, 15),
        "Handling": (-10, -5),
        "Ergonomics": (8, 15),
    },
    "stock_folding": {
        "VerticalRecoil": (-10, -5),
        "HorizontalRecoil": (-6, -2),
        "CameraRecoil": (-12, -5),
        "Convergence": (5, 12),
        "AimSpeed": (-6, -2),
        "AimStability": (5, 10),
        "Handling": (-3, 2),
        "Ergonomics": (4, 10),
    },
    "stock_ads_support": {
        "VerticalRecoil": (-8, -4),
        "HorizontalRecoil": (-5, -2),
        "CameraRecoil": (-8, -4),
        "Convergence": (6, 14),
        "AimSpeed": (-4, 0),
        "AimStability": (8, 15),
        "Handling": (-2, 5),
        "Ergonomics": (3, 8),
    },
    "stock_buttpad": {
        "VerticalRecoil": (-7, -2),
        "HorizontalRecoil": (-4, 0),
        "CameraRecoil": (-5, -1),
        "Convergence": (0, 0),
        "AimSpeed": (2, 8),
        "AimStability": (1, 8),
        "Handling": (2, 5),
        "Ergonomics": (4, 11),
    },
    # 兼容旧逻辑：stock 作为未细分时的中间档。
    "stock": {
        "VerticalRecoil": (-12, -7),
        "HorizontalRecoil": (-8, -4),
        "CameraRecoil": (-8, -5),
        "Convergence": (5, 18),
        "AimSpeed": (-5, 5),
        "AimStability": (7, 12),
        "Handling": (-2, 6),
        "Ergonomics": (8, 15),
    },
    # 缓冲管（buffer_adapter）
    "buffer_adapter": {
        "VerticalRecoil": (0, 5),
        "HorizontalRecoil": (0, 3),
        "Ergonomics": (-1, 5),
    },
    # 枪托适配器（stock_adapter）
    "stock_adapter": {
        "VerticalRecoil": (0, 0),
        "HorizontalRecoil": (0, 0),
        "CameraRecoil": (0, 0),
        "Convergence": (0, 0),
        "AimSpeed": (0, 0),
        "AimStability": (0, 0),
        "Handling": (0, 0),
        "Ergonomics": (0, 0),
    },
    "pistol_grip": {
        "VerticalRecoil": (-3, 1),
        "HorizontalRecoil": (-2, 2),
        "Ergonomics": (2, 7),
        "Accuracy": (0, 0),
        "AimSpeed": (1, 5),
        "AimStability": (1, 5),
        "Handling": (2, 8),
    },
    "foregrip": {
        "VerticalRecoil": (-9, -3),
        "HorizontalRecoil": (-6, -2),
        "CameraRecoil": (-7, -1),
        "Dispersion": (0, 0),
        "Convergence": (-5, 2),
        "AimSpeed": (3, 10),
        "AimStability": (5, 12),
        "Handling": (8, 18),
        "Ergonomics": (5, 16),
    },
    "receiver": {
        "AutoROF": (0, 2),
        "SemiROF": (0, 5),
        "ModMalfunctionChance": (-5, 5),
        "Accuracy": (-5, 5),
        "HeatFactor": (0.95, 1.05),
        "CoolFactor": (0.95, 1.05),
        "Ergonomics": (0, 7),
        "Convergence": (0, 10),
    },
    "mount": {
        "VerticalRecoil": (0, 0),
        "HorizontalRecoil": (0, 0),
        "Dispersion": (0, 0),
        "Ergonomics": (-1, 1),
        "AimStability": (0, 0),
        "Handling": (0, 0),
        "Accuracy": (0, 0),
        "HeatFactor": (0, 0),
        "CoolFactor": (0, 0),
    },
    "flashlight_laser": {
        "Ergonomics": (-2, 0),
        "Handling": (-4, -2),
    },
    "barrel_short": {
        "VerticalRecoil": (-2, 2),
        "HorizontalRecoil": (0, 2),
        "Dispersion": (5, 12),
        "CenterOfImpact": (0.05, 0.15),
        "Velocity": (-6, -2),
        "Accuracy": (-20, -5),
        "HeatFactor": (1.1, 1.3),
        "CoolFactor": (0.9, 0.95),
        "Convergence": (10, 25),
        "DurabilityBurnModificator": (1.1, 1.3),
        "RecoilAngle": (5, 15),
    },
    "barrel_medium": {
        "VerticalRecoil": (-4, -1),
        "HorizontalRecoil": (-3, 1),
        "Dispersion": (-1, 7),
        "CenterOfImpact": (0.02, 0.05),
        "Velocity": (-1, 3),
        "Accuracy": (-2, 5),
        "HeatFactor": (1, 1.15),
        "CoolFactor": (0.95, 1.05),
        "Convergence": (0, 10),
        "DurabilityBurnModificator": (0.95, 1.05),
        "RecoilAngle": (-5, 5),
    },
    "barrel_long": {
        "VerticalRecoil": (-6, -3),
        "HorizontalRecoil": (-5, -3),
        "Dispersion": (-8, -2),
        "CenterOfImpact": (0.005, 0.02),
        "Velocity": (4, 8),
        "Accuracy": (10, 25),
        "HeatFactor": (0.9, 1.1),
        "CoolFactor": (1, 1.15),
        "Convergence": (-15, -5),
        "DurabilityBurnModificator": (0.7, 0.9),
        "RecoilAngle": (-15, -5),
    },
    "handguard_short": {
        "VerticalRecoil": (-4, -1),
        "HorizontalRecoil": (-2, -1),
        "HeatFactor": (1.05, 1.1),
        "CoolFactor": (0.8, 0.95),
        "AimStability": (1, 5),
        "AimSpeed": (2, 8),
        "Handling": (5, 12),
        "Ergonomics": (4, 10),
        "DurabilityBurnModificator": (1.0, 1.0),
    },
    "handguard_medium": {
        "VerticalRecoil": (-8, -4),
        "HorizontalRecoil": (-6, -2),
        "HeatFactor": (0.95, 1.05),
        "CoolFactor": (0.90, 1.0),
        "AimStability": (5, 10),
        "AimSpeed": (0, 5),
        "Handling": (2, 8),
        "Ergonomics": (1, 6),
        "DurabilityBurnModificator": (1.0, 1.0),
    },
    "handguard_long": {
        "VerticalRecoil": (-12, -6),
        "HorizontalRecoil": (-8, -3),
        "HeatFactor": (0.88, 0.95),
        "CoolFactor": (0.85, 1.05),
        "AimStability": (10, 20),
        "AimSpeed": (-8, -2),
        "Handling": (-8, -2),
        "Ergonomics": (-5, 2),
        "DurabilityBurnModificator": (0.9, 1.0),
    },
}
