# -*- coding: utf-8 -*-
"""附件规则范围配置。

将附件规则范围独立到此文件，便于用户直接调整数值区间。
"""

# 附件规则范围（来自“附件属性规则指南”，仅在字段存在时夹紧）
MOD_PROFILE_RANGES = {
    "muzzle_suppressor": {
        "Ergonomics": (-18, -8),
        "CameraRecoil": (-8, -3),
        "VerticalRecoil": (-18, -10),
        "HorizontalRecoil": (-12, -6),
        "Dispersion": (-5, -1),
        "Accuracy": (-5, -1),
        "Velocity": (0.2, 1.0),
        "Loudness": (-40, -20),
        "Flash": (-80, -30),
        "ModMalfunctionChance": (10, 25),
        "DurabilityBurnModificator": (1.2, 1.5),
        "AimSpeed": (-20, -8),
    },
    "muzzle_flashhider": {
        "Ergonomics": (-5, -2),
        "CameraRecoil": (-2, -1),
        "VerticalRecoil": (-5, -2),
        "HorizontalRecoil": (-3, -1),
        "Dispersion": (-2, 2),
        "Loudness": (0, 10),
        "Flash": (-70, -40),
        "AimSpeed": (-3, -1),
    },
    "muzzle_brake": {
        "Ergonomics": (-8, -3),
        "CameraRecoil": (-10, -3),
        "VerticalRecoil": (-24, -14),
        "HorizontalRecoil": (-18, -10),
        "Dispersion": (-5, -2),
        "Accuracy": (-2, -1),
        "Velocity": (0.5, 1.0),
        "Loudness": (10, 20),
        "Flash": (3, 15),
        "AimSpeed": (-6, -2),
    },
    "muzzle_thread": {
        "Ergonomics": (0, 1),
        "CameraRecoil": (0, 0),
        "VerticalRecoil": (0, 0),
        "HorizontalRecoil": (0, 0),
        "Dispersion": (0, 0),
        "Accuracy": (0, 0),
        "Velocity": (0, 0),
        "Loudness": (0, 0),
        "Flash": (0, 0),
        "ModMalfunctionChance": (0, 0),
        "DurabilityBurnModificator": (1.0, 1.0),
        "AimSpeed": (0, 0),
    },
    "magazine": {
        "Ergonomics": (-25, -1),
        "ReloadSpeed": (-25, 5),
        "LoadUnloadModifier": (5, 15),
        "CheckTimeModifier": (1, 5),
        "MalfunctionChance": (-2, 5),
        "AimSpeed": (-8, -1),
        "Handling": (-8, -1),
    },
    "gasblock": {
        "Ergonomics": (-2, 0),
        "VerticalRecoil": (-2, 0),
        "HorizontalRecoil": (-1, 0),
        "ModMalfunctionChance": (-2, 5),
        "DurabilityBurnModificator": (0.95, 1.05),
        "HeatFactor": (0.98, 1.02),
        "CoolFactor": (0.98, 1.02),
    },
    "scope_magnified": {
        "AimSpeed": (-15, -5),
        "AimStability": (5, 20),
        "Ergonomics": (-12, -5),
        "Handling": (-10, -3),
    },
    "scope_red_dot": {
        "AimSpeed": (2, 8),
        "AimStability": (0, 5),
        "Ergonomics": (-3, 0),
    },
    "iron_sight": {
        "AimSpeed": (2, 10),
        "Ergonomics": (0, 2),
    },
    "stock": {
        "VerticalRecoil": (-18, -8),
        "HorizontalRecoil": (-12, -4),
        "CameraRecoil": (-20, -5),
        "Convergence": (5, 20),
        "AimSpeed": (-12, -2),
        "AimStability": (5, 15),
        "Handling": (-10, -2),
        "Ergonomics": (-15, -2),
    },
    "pistol_grip": {
        "Ergonomics": (2, 15),
        "AimSpeed": (1, 5),
        "AimStability": (1, 5),
        "Handling": (2, 8),
        "VerticalRecoil": (-5, -1),
    },
    "foregrip": {
        "VerticalRecoil": (-9, -3),
        "HorizontalRecoil": (-6, -2),
        "CameraRecoil": (-6, -1),
        "Convergence": (0, 5),
        "AimSpeed": (-2, 6),
        "AimStability": (5, 12),
        "Handling": (8, 18),
        "Ergonomics": (0, 8),
    },
    "receiver": {
        "AutoROF": (0, 2),
        "SemiROF": (0, 5),
        "ModMalfunctionChance": (-5, 5),
        "Accuracy": (-5, 5),
        "HeatFactor": (0.95, 1.05),
        "CoolFactor": (0.95, 1.05),
        "Ergonomics": (-2, 5),
        "Convergence": (0, 10),
    },
    "mount": {
        "Ergonomics": (-1, 1),
    },
    "flashlight_laser": {
        "Ergonomics": (-3, -1),
        "Handling": (-8, -2),
    },
    "barrel_short": {
        "CenterOfImpact": (0.05, 0.15),
        "Velocity": (-10, -2),
        "Accuracy": (-20, -5),
        "HeatFactor": (1.1, 1.3),
        "CoolFactor": (1.05, 1.2),
        "Convergence": (10, 25),
        "DurabilityBurnModificator": (1.1, 1.3),
        "RecoilAngle": (5, 15),
    },
    "barrel_medium": {
        "CenterOfImpact": (0.02, 0.05),
        "Velocity": (-2, 5),
        "Accuracy": (-2, 5),
        "HeatFactor": (0.95, 1.05),
        "CoolFactor": (0.95, 1.05),
        "Convergence": (0, 10),
        "DurabilityBurnModificator": (0.95, 1.05),
        "RecoilAngle": (-5, 5),
    },
    "barrel_long": {
        "CenterOfImpact": (0.005, 0.02),
        "Velocity": (5, 10),
        "Accuracy": (10, 25),
        "HeatFactor": (0.8, 0.95),
        "CoolFactor": (0.8, 0.95),
        "Convergence": (-15, -5),
        "DurabilityBurnModificator": (0.7, 0.9),
        "RecoilAngle": (-15, -5),
    },
    "handguard_short": {
        "VerticalRecoil": (-3, -1),
        "HorizontalRecoil": (-2, -1),
        "HeatFactor": (1.05, 1.1),
        "CoolFactor": (1.05, 1.15),
        "AimStability": (1, 5),
        "AimSpeed": (2, 8),
        "Handling": (5, 12),
        "Ergonomics": (2, 10),
        "DurabilityBurnModificator": (1.0, 1.0),
    },
    "handguard_medium": {
        "VerticalRecoil": (-10, -4),
        "HorizontalRecoil": (-6, -2),
        "HeatFactor": (0.95, 1.05),
        "CoolFactor": (0.95, 1.05),
        "AimStability": (5, 10),
        "AimSpeed": (0, 5),
        "Handling": (2, 8),
        "Ergonomics": (0, 5),
        "DurabilityBurnModificator": (1.0, 1.0),
    },
    "handguard_long": {
        "VerticalRecoil": (-18, -10),
        "HorizontalRecoil": (-12, -6),
        "HeatFactor": (0.85, 0.95),
        "CoolFactor": (0.85, 0.95),
        "AimStability": (10, 20),
        "AimSpeed": (-8, -2),
        "Handling": (-8, -2),
        "Ergonomics": (-5, -2),
        "DurabilityBurnModificator": (0.9, 1.0),
    },
}
